name: ci
on: [ push, pull_request ]
jobs:
  ci:
    name: Tests with TYPO3 ${{ matrix.typo3 }} PHP ${{ matrix.php }}
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        typo3: [ '^11.5', '^12.4', '^13.4' ]
        php: [ '8.0', '8.1', '8.2', '8.3' ]
        exclude:
          - typo3: '^11.5'
            php: '8.1'
          - typo3: '^11.5'
            php: '8.2'
          - typo3: '^11.5'
            php: '8.3'

          - typo3: '^12.4'
            php: '8.0'
          - typo3: '^12.4'
            php: '8.3'

          - typo3: '^13.4'
            php: '8.0'
          - typo3: '^13.4'
            php: '8.1'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup PHP version ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2
          coverage: none

      - name: Get composer cache directory
        id: composer-cache
        run: echo "COMPOSER_CACHE_DIRECTORY=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache composer dependencies
        uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.COMPOSER_CACHE_DIRECTORY }}
          key: ${{ runner.os }}-php-${{ matrix.php }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-php-${{ matrix.php }}-composer-

      - name: Install dependencies with typo3/cms-core:${{ matrix.typo3 }}
        run: |
          composer require typo3/cms-core:${{ matrix.typo3 }} --prefer-dist --no-progress --no-suggest --optimize-autoloader

      - name: Info
        run: composer info

      - name: Lint
        run: |
          composer run ci:lint:php
          composer run ci:lint:yaml

      - name: CGL
        run: composer run ci:cgl:check
        if: matrix.typo3 == '^12.4'

      - name: Psalm
        run: composer run ci:psalm
        if: matrix.typo3 == '^12.4' || matrix.typo3 == '^13.4'

      - name: PHPStan
        run: composer run ci:stan
        if: matrix.typo3 == '^12.4' || matrix.typo3 == '^13.4'

      #- name: Unit tests
      #  run: |
      #    phpdbg --version
      #    composer run ci:tests:unit:cover
      #  if: matrix.typo3 == '^12.4' || matrix.typo3 == '^13.4'

      - name: Functional tests
        run: composer run ci:tests:functional
        if: matrix.typo3 == '^12.4' || matrix.typo3 == '^13.4'
